fix(cloudfront flow): fixes the syntax of the s3 check conditional and directs error to stderr with exit code 1
FETH-47

diff --git a/.github/workflows/cloudfront.yaml b/.github/workflows/cloudfront.yaml
--- a/.github/workflows/cloudfront.yaml
+++ b/.github/workflows/cloudfront.yaml
@@ -119,10 +119,12 @@ jobs:
                 echo "-----------------------------------------------------------"
                 echo "checksum the static files @ s3 origin:\n"
                 num_objs=$(aws s3 ls ${{env.bucket}} --summarize | grep -oP '\d' | head -n 1)
-                if [[ $num_objs < 1]]; then
+                if [[ $num_objs > 1 ]]; then
                   echo "Successfully upload static files!!!"
+                  exit 0
                 else
-                  echo "Failed to upload static files"
+                  echo "Failed to upload static files" >&2
+                  exit 1
                 fi
                 echo "--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--.--"
                 echo "This is the web URL: ${{needs.build-frontend.outputs.cf_dns}}"
